### ISSUE TITLE
Is there a way to modify the specified object array value？

### ISSUE THREAD

**Issue by Linbubin** [zaaack/immuter#1]
i have a array `[{a: 1, b: 1}, {a: 2,b: 2}, {a: 3, b: 3}]`,
want to change it, to `[{a: 1, b: 2}, {a: 2,b: 2}, {a: 3, b: 3}] // {a: 1,b: 1} -> {a: 1, b: 2}`,
have some ways?

**Comment by zaaack** [comment]
Would this help?

```js

import { Struct, setIn } from 'immuter'

const struct = Struct({
 list: ([] as Array<{a: number, b: number}>)
})

const newStruct = struct.clone(s => {
  s.list = s.list.map(obj => obj.a === 1 ? setIn(obj, _ => _.b)(2) : obj)
})
```

**Comment by Linbubin** [comment]
@zaaack 
```
const struct = Struct({
 list: ([] as Array<{a: number, b: number}>)
})
```

What's the syntax in this code?  `<...>`

**Comment by zaaack** [comment]
@Linbubin It's typescript's type annotation.. you can ignore it.

**Comment by Linbubin** [comment]
```
var I = require('immuter');

const struct = I.Struct({
	list:[{a: 1, b: 1}, {a: 2,b: 2}, {a: 3, b: 3}]
});

const newStruct = struct.clone(s => {
  s.list = s.list.map(obj => obj.a === 1 ? I.setIn(obj, _ => _.b)(2) : obj)
})

console.log(newStruct);
```

```
hzjs@DESKTOP-2UJAGJE /e/test/immutable-test (master)
$ node index.js

{ list: [ { a: 1, b: 1 }, { a: 2, b: 2 }, { a: 3, b: 3 } ] }
```

the result is not change.

**Comment by zaaack** [comment]
@Linbubin Looks like `Proxy` triggered some strange behavior of V8. You can inspect struct by `Struct.debug(struct, true)`, or access it by `struct.list[0].b`, it should be modified. But it won't show in console.log.

**Comment by zaaack** [comment]
Struct is an experimental feature, it might have issues, you can use set/get/update/setIn, they are more stable and reliable.
